[package]
name = "ax_semantic"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ax_ast = { path = "../ax_ast" }
ax_core = { path = "../ax_core" }
ax_diag = { path = "../ax_diag" }
ax_effects = { path = "../ax_effects" }
ax_packs = { path = "../ax_packs" }

[dev-dependencies]
ax_parser = { path = "../ax_parser" }

[lib]
path = "src/lib.rs"
