[package]
name = "ax_test"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ax_ast = { path = "../ax_ast" }
ax_core = { path = "../ax_core" }
ax_diag = { path = "../ax_diag" }
ax_parser = { path = "../ax_parser" }
ax_semantic = { path = "../ax_semantic" }

[lib]
path = "src/lib.rs"
