#ifndef AX_RUNTIME_H
#define AX_RUNTIME_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  const char* method;
  const char* path;
  int response_kind;
  const char* body;
} ax_http_route;

typedef struct {
  const char* pattern;
  int is_wildcard;
  const char* response;
} ax_tcp_route;

typedef char* (*ax_tcp_text_handler)(void* state, const char* request);

void ax_io_println(const char* s);
void ax_io_print(const char* s);
void ax_io_eprintln(const char* s);
char* ax_io_read_line(void);
char* ax_fs_read_text(const char* path);
char* ax_fs_read_text_or(const char* path, const char* fallback);
char* ax_fs_read_text_limit(const char* path, int max_bytes);
char* ax_fs_read_text_range(const char* path, int offset, int max_bytes);
char* ax_fs_read_text_tail(const char* path, int max_bytes);
char* ax_fs_read_lines(const char* path, int start_line, int max_lines);
char* ax_fs_read_lines_json(const char* path, int start_line, int max_lines);
char* ax_fs_read_jsonl(const char* path, int start_line, int max_lines);
char* ax_fs_read_json(const char* path);
char* ax_fs_read_json_or(const char* path, const char* fallback_json);
char* ax_fs_read_base64(const char* path);
char* ax_fs_read_base64_range(const char* path, int offset, int max_bytes);
char* ax_fs_read_base64_tail(const char* path, int max_bytes);
void ax_fs_write_text(const char* path, const char* content);
void ax_fs_write_text_atomic(const char* path, const char* content);
void ax_fs_write_json_atomic(const char* path, const char* json);
void ax_fs_write_base64(const char* path, const char* data_base64);
void ax_fs_append_text(const char* path, const char* content);
void ax_fs_append_jsonl(const char* path, const char* json);
int ax_fs_exists(const char* path);
void ax_fs_remove(const char* path);
void ax_fs_mkdir(const char* path);
void ax_fs_mkdir_all(const char* path);
void ax_fs_ensure_parent(const char* path);
char* ax_fs_list(const char* path);
char* ax_fs_list_json(const char* path);
char* ax_fs_list_stat_json(const char* path);
char* ax_fs_walk(const char* path);
char* ax_fs_walk_json(const char* path);
char* ax_fs_walk_stat_json(const char* path);
char* ax_fs_find(const char* path, const char* needle);
char* ax_fs_glob(const char* path, const char* pattern);
void ax_fs_copy(const char* source, const char* target);
long long ax_fs_size(const char* path);
char* ax_fs_stat_json(const char* path);
char* ax_fs_cwd(void);
char* ax_fs_temp_dir(void);
void ax_fs_rename(const char* source, const char* target);
void ax_fs_remove_dir(const char* path);
int ax_fs_is_file(const char* path);
int ax_fs_is_dir(const char* path);
long long ax_fs_modified(const char* path);
char* ax_crypto_sha256_hex(const char* input);
char* ax_crypto_sha256_json(const char* input);
int ax_crypto_sha256_verify_hex(const char* input, const char* expected);
char* ax_crypto_hmac_sha256_hex(const char* key, const char* data);
char* ax_crypto_hmac_sha256_json(const char* key, const char* data);
int ax_crypto_hmac_sha256_verify_hex(const char* key, const char* data, const char* expected);
char* ax_crypto_hmac_sha256_file_hex(const char* key, const char* path);
char* ax_crypto_hmac_sha256_file_json(const char* key, const char* path);
int ax_crypto_hmac_sha256_file_verify_hex(const char* key, const char* path, const char* expected);
char* ax_crypto_hmac_sha256_file_range_hex(const char* key, const char* path, int offset, int max_bytes);
char* ax_crypto_hmac_sha256_file_range_json(const char* key, const char* path, int offset, int max_bytes);
int ax_crypto_hmac_sha256_file_range_verify_hex(
    const char* key, const char* path, int offset, int max_bytes, const char* expected);
char* ax_crypto_sha256_file_hex(const char* path);
char* ax_crypto_sha256_file_json(const char* path);
int ax_crypto_sha256_file_verify_hex(const char* path, const char* expected);
char* ax_crypto_sha256_file_range_hex(const char* path, int offset, int max_bytes);
char* ax_crypto_sha256_file_range_json(const char* path, int offset, int max_bytes);
int ax_crypto_sha256_file_range_verify_hex(const char* path, int offset, int max_bytes, const char* expected);
char* ax_crypto_base64_encode(const char* input);
char* ax_crypto_base64_decode(const char* input);
int ax_crypto_constant_time_eq(const char* left, const char* right);
char* ax_crypto_random_hex(int byte_count);
char* ax_crypto_random_base64url(int byte_count);
char* ax_crypto_uuid_v4(void);
char* ax_env_get(const char* name);
int ax_env_has(const char* name);
void ax_env_set(const char* name, const char* value);
char* ax_env_get_or(const char* name, const char* fallback);
char* ax_env_snapshot_json(const char* prefix);
int ax_env_load_dotenv(const char* path);
char* ax_env_load_dotenv_json(const char* path);
char* ax_process_exec(const char* command);
char* ax_process_exec_limit(const char* command, int max_bytes);
int ax_process_status(const char* command);
char* ax_process_run_json(const char* command, int max_bytes);
char* ax_process_run_log_json(const char* command, int max_bytes);
char* ax_process_run_lines_json(const char* command, int max_bytes);
char* ax_process_run_log_lines_json(const char* command, int max_bytes);
void ax_cli_init(int argc, char** argv);
int ax_cli_argc(void);
char* ax_cli_arg(int index);
int ax_cli_has(const char* name);
char* ax_cli_value(const char* name);
char* ax_cli_value_or(const char* name, const char* fallback);
char* ax_cli_args_json(void);
char* ax_cli_parse_json(void);
char* ax_json_escape(const char* value);
char* ax_json_quote(const char* value);
char* ax_json_pair(const char* key, const char* value_json);
char* ax_json_string_pair(const char* key, const char* value);
char* ax_json_set(const char* json, const char* key, const char* value_json);
char* ax_json_string_set(const char* json, const char* key, const char* value);
char* ax_json_remove(const char* json, const char* key);
char* ax_json_object(const char* fields);
char* ax_json_array(const char* items);
char* ax_json_array_push(const char* json, const char* value_json);
char* ax_json_string_array_push(const char* json, const char* value);
char* ax_json_compact(const char* json);
int ax_json_valid(const char* json);
char* ax_json_get(const char* json, const char* key);
char* ax_json_query(const char* json, const char* path);
char* ax_json_get_or(const char* json, const char* key, const char* fallback);
char* ax_json_query_or(const char* json, const char* path, const char* fallback);
int ax_json_has(const char* json, const char* key);
int ax_json_query_has(const char* json, const char* path);
int ax_json_int(const char* json, const char* key);
int ax_json_bool(const char* json, const char* key);
int ax_json_query_int(const char* json, const char* path);
int ax_json_query_bool(const char* json, const char* path);
int ax_json_contains(const char* json, const char* key, const char* needle);
int ax_json_query_contains(const char* json, const char* path, const char* needle);
char* ax_json_kind(const char* json, const char* key);
char* ax_json_query_kind(const char* json, const char* path);
char* ax_json_keys(const char* json);
char* ax_json_keys_json(const char* json);
char* ax_json_query_keys_json(const char* json, const char* path);
int ax_json_len(const char* json, const char* key);
int ax_json_query_len(const char* json, const char* path);
char* ax_json_at(const char* json, const char* key, int index);
char* ax_json_query_at(const char* json, const char* path, int index);
int ax_str_len(const char* value);
int ax_str_eq(const char* left, const char* right);
int ax_str_contains(const char* value, const char* needle);
int ax_str_index_of(const char* value, const char* needle);
int ax_str_count(const char* value, const char* needle);
int ax_str_starts_with(const char* value, const char* prefix);
int ax_str_ends_with(const char* value, const char* suffix);
char* ax_str_trim(const char* value);
char* ax_str_upper(const char* value);
char* ax_str_lower(const char* value);
char* ax_str_concat(const char* left, const char* right);
char* ax_str_repeat(const char* value, int count);
char* ax_str_replace(const char* value, const char* needle, const char* replacement);
char* ax_str_slice(const char* value, int start, int length);
char* ax_str_split_json(const char* value, const char* delimiter);
char* ax_str_lines_json(const char* value);
char* ax_str_from_i64(long long value);
long long ax_str_parse_i64(const char* value);
int ax_str_parse_i32(const char* value);
char* ax_str_token(const char* value, int index);
char* ax_str_token_upper(const char* value, int index);
char* ax_str_line(const char* value, int index);
char* ax_path_normalize(const char* value);
char* ax_path_join(const char* left, const char* right);
char* ax_path_basename(const char* value);
char* ax_path_dirname(const char* value);
char* ax_path_extname(const char* value);
char* ax_path_stem(const char* value);
int ax_path_is_absolute(const char* value);
char* ax_url_encode(const char* value);
char* ax_url_decode(const char* value);
char* ax_url_query_get(const char* value, const char* key);
char* ax_url_query_or(const char* value, const char* key, const char* fallback);
int ax_url_query_has(const char* value, const char* key);
char* ax_url_query_json(const char* value);
char* ax_url_path(const char* value);
char* ax_url_host(const char* value);
char* ax_url_scheme(const char* value);
char* ax_http_get_json(const char* url, int max_bytes);
char* ax_http_post_json(const char* url, const char* body, int max_bytes);
long long ax_time_now(void);
long long ax_time_now_ms(void);
char* ax_time_iso_utc(long long epoch_seconds);
void ax_time_sleep_ms(int milliseconds);
void* ax_heap_alloc(int size);
void ax_heap_free(void* ptr);
void ax_panic(const char* message);
void* ax_async_spawn(void* entry);
void* ax_async_spawn_with_context(void* entry, void* context);
void* ax_async_context_new(int count);
void ax_async_context_set_i32(void* context, int index, int value);
void ax_async_context_set_i64(void* context, int index, long long value);
void ax_async_context_set_f64(void* context, int index, double value);
void ax_async_context_set_ptr(void* context, int index, void* value);
int ax_async_context_get_i32(void* context, int index);
long long ax_async_context_get_i64(void* context, int index);
double ax_async_context_get_f64(void* context, int index);
void* ax_async_context_get_ptr(void* context, int index);
void ax_async_await_void(void* future);
int ax_async_await_i32(void* future);
long long ax_async_await_i64(void* future);
double ax_async_await_f64(void* future);
void* ax_async_await_ptr(void* future);
void ax_async_cancel(void* future);
void ax_async_detach(void* future);
void* ax_async_box_i32(int value);
void* ax_async_box_i64(long long value);
void* ax_async_box_f64(double value);
void* ax_async_box_bool(int value);
int ax_tcp_ping_server(int port);
int ax_tcp_server_start(int port, const ax_tcp_route* routes, int route_count);
int ax_tcp_tls_server_start(int port, const ax_tcp_route* routes, int route_count);
void* ax_tcp_listen(int port);
void* ax_tcp_listen_on(const char* host, int port);
void* ax_tcp_connect(const char* host, int port);
int ax_tcp_serve_text(void* server, void* state, ax_tcp_text_handler handler, int workers);
void* ax_tcp_accept(void* server);
char* ax_tcp_read_text(void* conn, int max_bytes);
void ax_tcp_write_text(void* conn, const char* text);
char* ax_tcp_request_text(void* conn, const char* text, int max_bytes);
void ax_tcp_close(void* conn);
int ax_http_server_start(int port, const ax_http_route* routes, int route_count);
int ax_http_tls_server_start(int port, const ax_http_route* routes, int route_count);
char* ax_http_get(const char* url);
char* ax_http_post(const char* url, const char* body);
void* ax_map_new(int capacity);
void ax_map_set(void* map, const char* key, const char* value);
char* ax_map_get(void* map, const char* key);
int ax_map_has(void* map, const char* key);
int ax_map_del(void* map, const char* key);
int ax_map_len(void* map);
void ax_map_clear(void* map);

#ifdef __cplusplus
}
#endif

#endif
